//
//  HalvingRewardChart.swift
//  BitcoinWidgets
//
//  Display the Block Reward halving steps over time.
//

import SwiftUI
import Charts

struct HalvingRewardChart: View {
    let currentBlockHeight: Int

    /// Bound to the enclosing screen so it can `.scrollDisabled(_:)` its ScrollView
    /// while the user is scrubbing this chart, so a drag started on the chart is
    /// never torn between scrolling and scrubbing. Optional — defaults to a
    /// throwaway binding so the chart still works when embedded without one.
    @Binding var isScrubbing: Bool

    init(currentBlockHeight: Int, isScrubbing: Binding<Bool> = .constant(false)) {
        self.currentBlockHeight = currentBlockHeight
        self._isScrubbing = isScrubbing
    }

    // Halving interval is 210,000 blocks
    private let halvingInterval = 210_000

    /// Block height currently under the finger (data domain). Driven and cleared by
    /// Charts via `.chartXSelection`; nil when not scrubbing.
    @State private var selectedHeight: Int?
    /// Halving era of the last selection, so the scrub haptic ticks once per halving
    /// crossed — here that lines up exactly with each visible reward "cliff".
    @State private var lastEra: Int?
    /// The current scrub readout, shown in the card header (NOT an in-chart bubble) to
    /// match the time-series charts. Internal @State so per-tick updates re-render only
    /// this chart, never the host screen — and the plot layout is never touched.
    @State private var sample: BlockScrubSample?

    /// Log y-scale floor — matches the `.chartYScale` domain minimum. Reward values
    /// below it (the deep sub-satoshi tail past ~era 35) are clamped to it so neither
    /// the curve nor the scrub/Now dots ever render beneath the visible plot.
    private static let rewardFloor = 0.000000001

    private struct RewardPoint: Identifiable {
        let id = UUID()
        let blockHeight: Int
        let reward: Double
    }

    private var halvingHeights: [Int] {
        // All 33 halvings (approx end of emission)
        (1...33).map { $0 * halvingInterval }
    }

    /// The reward step-curve, generated by stepping every era across the full X
    /// domain (flat segment per era + a vertical cliff to the next). Because each
    /// era's flat level equals `reward(at:)` for every height in it, the scrub dot —
    /// placed at the exact reward for the touched height — lands flush on the drawn
    /// step everywhere it is visible.
    private static let rewardPoints: [RewardPoint] = {
        var points: [RewardPoint] = []
        var reward: Double = 50.0
        var i = 0

        while i * 210_000 <= BlockChartScrub.domainMax {
            let startHeight = i * 210_000
            let endHeight = min((i + 1) * 210_000, BlockChartScrub.domainMax)
            // Clamp to the log floor so the deep tail bottoms out flush at the plot
            // base instead of plunging below it (keeps the scrub dot on the line).
            let plotted = max(reward, HalvingRewardChart.rewardFloor)

            // Start of era
            points.append(RewardPoint(blockHeight: startHeight, reward: plotted))
            // End of era (cliff edge)
            points.append(RewardPoint(blockHeight: endHeight, reward: plotted))

            reward /= 2
            i += 1
        }

        return points
    }()

    /// Block height under the finger, clamped to the drawn X domain. nil when idle.
    private var clampedSelectedHeight: Int? {
        guard let h = selectedHeight else { return nil }
        return min(max(h, 0), BlockChartScrub.domainMax)
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            BlockScrubHeader(title: "Block Reward Schedule", sample: sample)
            chartCanvas
        }
    }

    private var chartCanvas: some View {
        Chart {
            // Vertical Lines for Halvings
            // Filter to show fewer lines to avoid crowding
            ForEach(halvingHeights, id: \.self) { height in
                if height % (210_000 * 4) == 0 { // Every 4th halving line
                    RuleMark(x: .value("Halving", height))
                        .foregroundStyle(.white.opacity(0.03))
                        .lineStyle(StrokeStyle(lineWidth: 1, dash: [4]))
                }
            }
            
            // Reward Steps (Square Wave)
            ForEach(Self.rewardPoints) { point in
                LineMark(
                    x: .value("Block Height", point.blockHeight),
                    y: .value("Block Reward", point.reward)
                )
                .foregroundStyle(
                    LinearGradient(
                        colors: [.orange, .orange.opacity(0.1)],
                        startPoint: .leading,
                        endPoint: .trailing
                    )
                )
                .interpolationMethod(.linear)
                .lineStyle(StrokeStyle(lineWidth: 1.5, lineCap: .round, lineJoin: .round)) // Slightly thinner for more steps
            }
            
            // Current Position dashed line — hidden while scrubbing so the scrub
            // cursor reads as the active marker (the pulsing "Now" dot below stays).
            if clampedSelectedHeight == nil {
                RuleMark(x: .value("Current", currentBlockHeight))
                    .foregroundStyle(.orange.opacity(0.8))
                    .lineStyle(StrokeStyle(lineWidth: 1, dash: [4]))
            }

            // Pulsing "Now" dot — ALWAYS drawn (even while scrubbing) so the
            // reference point for the current reward is never lost.
            PointMark(
                x: .value("Current", currentBlockHeight),
                y: .value("Reward", max(Self.reward(at: currentBlockHeight), Self.rewardFloor))
            )
            .symbol {
                PulsingDotView()
            }

            // Scrub cursor — rule + flush dot at the touched height (the value readout
            // is surfaced in the header, not in-chart). The value is the exact reward
            // for that height, so scrubbing left shows past rewards and right the
            // projected future halvings. Drawn last, on top.
            if let h = clampedSelectedHeight {
                let rewardHere = Self.reward(at: h)

                RuleMark(x: .value("Selected", h))
                    .foregroundStyle(Color.bitcoinOrange.opacity(0.5))
                    .lineStyle(StrokeStyle(lineWidth: 1, dash: [4]))

                PointMark(
                    x: .value("Selected", h),
                    y: .value("Reward", max(rewardHere, Self.rewardFloor))
                )
                .foregroundStyle(Color.bitcoinOrange)
                .symbolSize(160)
                .annotation(position: .overlay, spacing: 0) {
                    Circle()
                        .fill(Color.bitcoinOrange)
                        .frame(width: 11, height: 11)
                        .overlay(Circle().stroke(.background, lineWidth: 2))
                }
            }
        }
        .chartXSelection(value: $selectedHeight)
        .onChange(of: selectedHeight) { _, newValue in
            updateScrub(to: newValue)
        }
        // Custom X Axis
        .chartXAxis {
            // Simplified steps: 0, 2M, 4M, 6M
            let values = [0, 2_000_000, 4_000_000, 6_000_000]
            AxisMarks(values: values) { value in
                if let intValue = value.as(Int.self) {
                     // Remove ticks
                     AxisTick(stroke: StrokeStyle(lineWidth: 0))
                    
                     AxisValueLabel {
                         Text(intValue == 0 ? "0" : "\(intValue / 1_000_000)M")
                             .font(.system(size: 9))
                             .foregroundStyle(.secondary)
                     }
                }
            }
        }
        .chartXScale(domain: 0...7_600_000)
        // Custom Y Axis
        .chartYAxis {
            // Log steps
            let values = [50.0, 0.1, 0.001, 0.00001, 0.00000001]
            AxisMarks(position: .leading, values: values) { value in
                 AxisGridLine(stroke: StrokeStyle(lineWidth: 0.5))
                     .foregroundStyle(.white.opacity(0.05))
                 
                 if let doubleValue = value.as(Double.self) {
                     AxisValueLabel {
                         Text(formatRewardLabel(doubleValue))
                             .font(.system(size: 8, weight: .medium, design: .monospaced))
                             .foregroundStyle(.secondary.opacity(0.8))
                     }
                 }
            }
        }
        .chartYScale(domain: 0.000000001...100, type: .log)
        .frame(height: 220)
    }
    
    /// Closed-form block reward at a height: 50 BTC halved once per 210k-block era.
    /// Used for the rendered step, the "Now" dot and the scrub dot so all agree.
    static func reward(at height: Int) -> Double {
        let era = max(0, height) / 210_000
        return 50.0 / pow(2.0, Double(era))
    }

    /// Readout text for a reward: BTC while sizeable, sats once it drops below
    /// 0.01 BTC, and "< 1 sat" for the sub-satoshi deep-future tail — so the scrub
    /// chip never shows a misleading "0,00000000 BTC".
    private func rewardReadout(_ reward: Double) -> String {
        if reward >= 0.01 { return Formatters.formatBTC(reward) }
        let sats = reward * 100_000_000
        if sats >= 1 { return Formatters.formatAmount(Int(sats.rounded())) + " sats" }
        return "< 1 sat"
    }

    /// Reacts to a new `.chartXSelection` value: drives the `isScrubbing` gate and
    /// fires a selection haptic once per halving era crossed (including the first
    /// touch). A nil value (finger lifted) ends the scrub and resets the era tracker.
    private func updateScrub(to newValue: Int?) {
        guard let raw = newValue else {
            sample = nil
            if isScrubbing { isScrubbing = false }
            lastEra = nil
            return
        }
        let clamped = min(max(raw, 0), BlockChartScrub.domainMax)
        let era = clamped / BlockChartScrub.halvingInterval
        if era != lastEra {
            Haptics.selection()
            lastEra = era
        }
        sample = BlockScrubSample(
            value: rewardReadout(Self.reward(at: clamped)),
            context: BlockChartScrub.context(forHeight: clamped, currentHeight: currentBlockHeight)
        )
        if !isScrubbing { isScrubbing = true }
    }
    
    private func formatRewardLabel(_ value: Double) -> String {
        if value < 0.0000001 {
            return "1 sat"
        }
        if value < 0.001 {
            // Use more decimals for small numbers to avoid "0"
            let formatter = NumberFormatter()
            formatter.numberStyle = .decimal
            formatter.maximumFractionDigits = 8
            return formatter.string(from: NSNumber(value: value)) ?? "\(value)"
        }
        // Standard concise formatting for larger numbers
        let formatter = NumberFormatter()
        formatter.numberStyle = .decimal
        formatter.maximumFractionDigits = 1
        return formatter.string(from: NSNumber(value: value)) ?? "\(value)"
    }
}

// Reuse the pulsing dot for consistency
private struct PulsingDotView: View {
    @State private var isPulsing = false
    
    var body: some View {
        ZStack {
            // Signal Ring
            Circle()
                .stroke(Color.orange.opacity(0.5), lineWidth: 2)
                .frame(width: 8, height: 8)
                .scaleEffect(isPulsing ? 2.5 : 1.0)
                .opacity(isPulsing ? 0.0 : 1.0)
            
            // Core
            Circle()
                .fill(.orange)
                .frame(width: 6, height: 6) // Slightly smaller dot
                .shadow(color: .orange, radius: 4, x: 0, y: 0)
        }
        .onAppear {
            withAnimation(.easeOut(duration: 2.0).repeatForever(autoreverses: false)) {
                isPulsing = true
            }
        }
    }
}
